/**
 * The keeper: a small process that owns a Claude CLI so the server does not.
 *
 * A Claude session used to be a child of the server, holding the server's
 * pipes. Quit CH3 and the CLI either got SIGTERM and took its background
 * agents with it, or — when the two-second grace ran out first — kept running
 * with nobody listening, invisible, until the next message started a second
 * CLI on the same transcript. Either way a helper agent mid-task was lost.
 *
 * The keeper sits between the two. It spawns the CLI with its own pipes,
 * journals every line the CLI prints under a sequence number, and serves that
 * journal over a Unix socket. The server connects, says how far it had read,
 * and receives everything since — then the live tail. Server gone, socket
 * closed, CLI none the wiser; server back, socket reopened, nothing missed.
 *
 * The one thing the SDK insists on when it thinks it spawned a process is an
 * `initialize` handshake. The keeper remembers the CLI's answer to the first
 * one and answers every later one itself, so a reattached server gets the
 * greeting it expects from a CLI that was greeted an hour ago.
 *
 * Written to disk at runtime and run under the same Node the server runs on
 * (`ELECTRON_RUN_AS_NODE=1` in the desktop) — the pattern the account shim
 * already uses, because the packaged server is one bundled file and a second
 * entry point is not something the build produces.
 *
 * @module provider/keeper/claudeKeeperScript
 */

/** The file name the keeper is written under, inside the server's shim directory. */
export const CLAUDE_KEEPER_SCRIPT_FILENAME = "claude-keeper.mjs";

/**
 * The wire protocol, both directions, one JSON object per line.
 *
 * Client → keeper:
 * - `{"t":"hello","since":N}` — first message. Replays every journaled line
 *   with a sequence above N, then streams live.
 * - `{"t":"in","line":S}` — a line for the CLI's stdin. An `initialize`
 *   control request is answered from the cache when there is one.
 * - `{"t":"ack","seq":N}` — the server has processed everything up to N.
 * - `{"t":"end"}` — close the CLI's stdin (the SDK's graceful close).
 * - `{"t":"kill","signal":S}` — signal the CLI.
 *
 * Keeper → client:
 * - `{"t":"welcome","cliPid":N,"lastSeq":N,"exit":null|{code,signal}}`
 * - `{"t":"out","seq":N,"line":S}` — one CLI stdout line.
 * - `{"t":"exit","code":N|null,"signal":S|null}` — the CLI is gone.
 */
export const CLAUDE_KEEPER_PROTOCOL_VERSION = 1;

/**
 * The keeper's source. Plain ESM JavaScript with no dependencies, so the
 * server can write it anywhere and run it under any Node.
 *
 * Arguments: `--meta <path> --journal <path> --socket <path> --stderr <path>
 * [--cwd <dir>] -- <command> [args...]`. The environment is inherited as
 * given by the spawner.
 */
export const CLAUDE_KEEPER_SCRIPT = String.raw`#!/usr/bin/env node
// Generated by CH3. See apps/server/src/provider/keeper/claudeKeeperScript.ts.
import { spawn } from "node:child_process";
import { appendFileSync, createReadStream, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { dirname } from "node:path";
import { createInterface } from "node:readline";

const PROTOCOL_VERSION = 1;
const ACK_WRITE_INTERVAL_MS = 1000;
const LINGER_AFTER_EXIT_MS = 30000;
const KILL_ESCALATION_MS = 8000;
// How long a keeper waits, with nobody connected, before it gives up and takes
// the CLI with it. Detach is meant to survive a restart, not a machine: a
// worktree whose .ch3 was deleted, an instance that was renamed, a dev
// server someone Ctrl-C'd and never came back to, all used to leave a CLI
// resident forever holding its stdin open. Two hours is far longer than any
// restart and far shorter than forever. Overridden only by --idle-ms, which
// the tests pass and the server never does.
const DETACHED_TTL_MS = 2 * 60 * 60 * 1000;

function parseArgs(argv) {
  const options = { cwd: undefined };
  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];
    if (arg === "--") {
      options.command = argv[i + 1];
      options.args = argv.slice(i + 2);
      break;
    }
    const value = argv[i + 1];
    if (arg === "--meta") options.meta = value;
    else if (arg === "--journal") options.journal = value;
    else if (arg === "--socket") options.socket = value;
    else if (arg === "--stderr") options.stderr = value;
    else if (arg === "--cwd") options.cwd = value;
    else if (arg === "--owner") options.owner = value;
    else if (arg === "--idle-ms") options.idleMs = Number(value);
    i += 2;
  }
  if (!options.meta || !options.journal || !options.socket || !options.stderr || !options.command || !options.owner) {
    process.stderr.write("claude-keeper: missing arguments\n");
    process.exit(2);
  }
  return options;
}

const options = parseArgs(process.argv.slice(2));
mkdirSync(dirname(options.meta), { recursive: true });
mkdirSync(dirname(options.journal), { recursive: true });

let lastSeq = 0;
let lastAck = 0;
let ackDirty = false;
let initResponse = null;
let pendingInitRequestId = null;
let cliSessionId = null;
let exit = null;
let client = null;
let finishOnCliExit = false;

const startedAt = new Date().toISOString();

function writeMeta() {
  // The thread's meta file belongs to whichever keeper the server last stamped
  // this directory for. The stamp is written by the server between clearing
  // the directory and spawning, so it is already there before any keeper can
  // write: a keeper that has been retired reads a stamp that is not its own —
  // or, in the instant before the new one is stamped, no stamp at all — and
  // keeps its acks and its exit out of a file that is no longer its business.
  //
  // Comparing pids instead is a race, and it loses in the direction that
  // costs a CLI: the dying keeper writes first into the empty directory, the
  // live keeper is then locked out of its own meta for good, and the next boot
  // reads a dead pid with an exit and abandons a keeper that is still holding
  // a running CLI.
  try {
    const stamped = readFileSync(options.meta + ".owner", "utf8").trim();
    if (stamped !== options.owner) return;
    const meta = {
      version: PROTOCOL_VERSION,
      keeperPid: process.pid,
      cliPid: cli.pid ?? null,
      socketPath: options.socket,
      journalPath: options.journal,
      startedAt,
      lastSeq,
      lastAck,
      initResponse,
      cliSessionId,
      exit,
    };
    const tmp = options.meta + ".tmp";
    writeFileSync(tmp, JSON.stringify(meta));
    renameSync(tmp, options.meta);
  } catch {}
}

function send(message) {
  if (!client || client.destroyed) return;
  client.write(JSON.stringify(message) + "\n");
}

function journal(line) {
  lastSeq += 1;
  appendFileSync(options.journal, lastSeq + "\t" + line + "\n");
  send({ t: "out", seq: lastSeq, line });
  return lastSeq;
}

function readSessionId(line) {
  const match = /"session_id":"([0-9a-f-]{36})"/.exec(line);
  return match ? match[1] : null;
}

const cli = spawn(options.command, options.args, {
  cwd: options.cwd,
  env: process.env,
  stdio: ["pipe", "pipe", "pipe"],
  windowsHide: true,
});

cli.on("error", (error) => {
  appendFileSync(options.stderr, "[keeper] spawn error: " + String(error && error.message) + "\n");
  exit = { code: null, signal: null, error: String(error && error.message), at: new Date().toISOString() };
  writeMeta();
  send({ t: "exit", code: null, signal: null });
  scheduleShutdown();
});

cli.stderr.on("data", (chunk) => {
  appendFileSync(options.stderr, chunk);
});

const stdoutLines = createInterface({ input: cli.stdout, crlfDelay: Infinity });
stdoutLines.on("line", (line) => {
  if (line.length === 0) return;
  if (cliSessionId === null) {
    const sessionId = readSessionId(line);
    if (sessionId !== null) {
      cliSessionId = sessionId;
      writeMeta();
    }
  }
  if (pendingInitRequestId !== null && line.includes('"control_response"') && line.includes(pendingInitRequestId)) {
    initResponse = line;
    pendingInitRequestId = null;
    writeMeta();
  }
  journal(line);
});

cli.on("exit", (code, signal) => {
  exit = { code, signal, at: new Date().toISOString() };
  writeMeta();
  send({ t: "exit", code, signal });
  if (!finishOnCliExit) { scheduleShutdown(); return; }
  // Retired: the exit frame is flushed to whoever is listening, then the
  // keeper goes at once rather than lingering for a server that gave it up.
  if (client && !client.destroyed) client.end(finish); else finish();
});

// The one way this keeper ends its CLI on purpose: the exit is recorded and
// sent like any other, so the last meta says how the CLI went rather than
// nothing, and a server still connected hears it.
function retire() {
  if (exit !== null) { finish(); return; }
  finishOnCliExit = true;
  try { cli.kill("SIGTERM"); } catch {}
  const escalate = setTimeout(() => { if (exit === null) { try { cli.kill("SIGKILL"); } catch {} } }, KILL_ESCALATION_MS);
  escalate.unref();
}

const idleTtlMs = Number.isFinite(options.idleMs) && options.idleMs > 0 ? options.idleMs : DETACHED_TTL_MS;
let idleTimer = null;
function clearIdleTimer() {
  if (idleTimer !== null) { clearTimeout(idleTimer); idleTimer = null; }
}
// Armed whenever nobody is connected, cleared the moment somebody is. A
// keeper with a server attached never expires, however long the turn runs.
function armIdleTimer() {
  clearIdleTimer();
  if (exit !== null) return;
  idleTimer = setTimeout(() => {
    if (exit !== null || (client && !client.destroyed)) return;
    appendFileSync(options.stderr, "[keeper] no server for " + idleTtlMs + "ms; retiring\n");
    retire();
  }, idleTtlMs);
  idleTimer.unref();
}

let shutdownTimer = null;
function scheduleShutdown() {
  if (shutdownTimer !== null) return;
  shutdownTimer = setTimeout(finish, LINGER_AFTER_EXIT_MS);
  shutdownTimer.unref();
}

function finish() {
  try { server.close(); } catch {}
  try { if (existsSync(options.socket)) unlinkSync(options.socket); } catch {}
  writeMeta();
  process.exit(0);
}

/** A control request that the keeper answers itself, or null to forward. */
function cachedInitializeAnswer(line) {
  if (initResponse === null) return null;
  if (!line.includes('"control_request"') || !line.includes('"initialize"')) return null;
  let request;
  try { request = JSON.parse(line); } catch { return null; }
  if (!request || request.type !== "control_request" || !request.request || request.request.subtype !== "initialize") return null;
  let cached;
  try { cached = JSON.parse(initResponse); } catch { return null; }
  cached.response = { ...cached.response, request_id: request.request_id };
  return JSON.stringify(cached);
}

function rememberInitializeRequest(line) {
  if (initResponse !== null || pendingInitRequestId !== null) return;
  if (!line.includes('"control_request"') || !line.includes('"initialize"')) return;
  try {
    const request = JSON.parse(line);
    if (request && request.type === "control_request" && request.request && request.request.subtype === "initialize") {
      pendingInitRequestId = String(request.request_id);
    }
  } catch {}
}

function replayJournal(since, socket) {
  if (!existsSync(options.journal)) return Promise.resolve();
  return new Promise((resolve) => {
    const lines = createInterface({ input: createReadStream(options.journal), crlfDelay: Infinity });
    lines.on("line", (entry) => {
      const tab = entry.indexOf("\t");
      if (tab < 0) return;
      const seq = Number(entry.slice(0, tab));
      if (!Number.isFinite(seq) || seq <= since) return;
      if (socket.destroyed) return;
      socket.write(JSON.stringify({ t: "out", seq, line: entry.slice(tab + 1) }) + "\n");
    });
    lines.on("close", resolve);
  });
}

function handleClientMessage(message) {
  switch (message.t) {
    case "in": {
      const line = String(message.line ?? "");
      const answer = cachedInitializeAnswer(line);
      if (answer !== null) {
        journal(answer);
        return;
      }
      rememberInitializeRequest(line);
      if (cli.stdin.writable) cli.stdin.write(line + "\n");
      return;
    }
    case "ack": {
      const seq = Number(message.seq);
      if (Number.isFinite(seq) && seq > lastAck) {
        lastAck = seq;
        ackDirty = true;
      }
      return;
    }
    case "end": {
      try { cli.stdin.end(); } catch {}
      return;
    }
    case "kill": {
      const signal = typeof message.signal === "string" ? message.signal : "SIGTERM";
      try { cli.kill(signal); } catch {}
      if (signal !== "SIGKILL") {
        const escalate = setTimeout(() => { if (exit === null) { try { cli.kill("SIGKILL"); } catch {} } }, KILL_ESCALATION_MS);
        escalate.unref();
      }
      return;
    }
    default:
      return;
  }
}

const server = createServer((socket) => {
  // One server at a time. A new connection is the new server; the old one,
  // if any, is gone or about to be.
  if (client && !client.destroyed) client.destroy();
  client = socket;
  clearIdleTimer();
  let buffer = "";
  let greeted = false;
  socket.on("data", (chunk) => {
    buffer += chunk.toString();
    let newline;
    while ((newline = buffer.indexOf("\n")) >= 0) {
      const raw = buffer.slice(0, newline);
      buffer = buffer.slice(newline + 1);
      if (raw.length === 0) continue;
      let message;
      try { message = JSON.parse(raw); } catch { continue; }
      if (!greeted) {
        if (message.t !== "hello") continue;
        greeted = true;
        // The client tells us how far it got from meta.json, which is
        // written at most once a second. This keeper's own lastAck is the
        // same number without the lag — it was set by the previous server's
        // ack frames and has survived that server — so replaying from the
        // lower of the two would re-deliver up to a second of already
        // processed messages, and nothing downstream is idempotent: the
        // assistant text and the tool rows would simply appear twice.
        const claimed = Number.isFinite(Number(message.since)) ? Number(message.since) : 0;
        const since = Math.max(claimed, lastAck);
        socket.write(JSON.stringify({ t: "welcome", version: PROTOCOL_VERSION, cliPid: cli.pid ?? null, lastSeq, exit }) + "\n");
        // Live lines that arrive during the replay are held back so the
        // sequence stays ascending on the wire.
        const held = [];
        // The stand-in carries its socket so the close handler below can
        // recognise it. Without that, a server that disappeared mid-replay
        // left this object installed as the client for the life of the keeper,
        // and every CLI line after it was pushed into held and never read.
        const holding = {
          socket,
          write: (line) => held.push(line),
          get destroyed() { return socket.destroyed; },
          destroy: () => socket.destroy(),
        };
        client = holding;
        replayJournal(since, socket).then(() => {
          if (socket.destroyed) {
            if (client === holding) client = null;
            return;
          }
          for (const line of held) socket.write(line);
          client = socket;
          if (exit !== null) socket.write(JSON.stringify({ t: "exit", code: exit.code, signal: exit.signal }) + "\n");
        });
        continue;
      }
      handleClientMessage(message);
    }
  });
  socket.on("error", () => {});
  socket.on("close", () => {
    if (client === socket || (client && client.socket === socket)) {
      client = null;
      armIdleTimer();
    }
  });
});

try { if (existsSync(options.socket)) unlinkSync(options.socket); } catch {}
server.listen(options.socket, () => {
  writeMeta();
  armIdleTimer();
});
server.on("error", (error) => {
  appendFileSync(options.stderr, "[keeper] socket error: " + String(error && error.message) + "\n");
});

const ackTimer = setInterval(() => {
  if (!ackDirty) return;
  ackDirty = false;
  writeMeta();
}, ACK_WRITE_INTERVAL_MS);
ackTimer.unref();

// The keeper's own death must not be the CLI's. Whoever signals the keeper
// gets the CLI signalled too, so a kill is still a kill; only the server's
// disappearance — a socket closing — is not.
for (const signal of ["SIGTERM", "SIGINT", "SIGHUP"]) {
  process.on(signal, () => { retire(); });
}
`;
