#!/bin/sh
# Hygiene gate: the checks that are about what a file *is*, not whether it
# compiles. Ported from the pre-commit hooks Bauhog runs
# (check-added-large-files, detect-private-key) plus the two rules that are
# CH3's own: `.env` must never be committed, and shipped server code logs
# through the structured logger rather than `console.log`.
#
# One script, two callers, so the commit hook and CI cannot drift apart:
#
#   sh scripts/git-hygiene.sh <path>...   # the pre-commit hook, staged files
#   sh scripts/git-hygiene.sh --all       # CI, every tracked file
#
# POSIX sh on purpose: it runs on every commit, so it may not pay for a Node
# start-up, and it must behave the same in a developer's macOS shell and on the
# Linux runner. Paths with spaces are real here ("LLM coding agent documents"),
# which is why every expansion is quoted and no filename is ever parsed back
# out of a command's output.
set -u

# 4 MiB. The largest file this repo legitimately tracks is a 1024px brand icon
# at 2,899,990 bytes (assets/, regenerated by `vp run icons:export`), so the
# threshold has to clear that; 4 MiB leaves headroom for the next icon export
# while staying far below the artifacts this is here to stop — a dmg, a screen
# recording, a SQLite snapshot of somebody's CH3 home. Because the limit
# sits above everything legitimate, "files added" and "all tracked files" give
# the same answer, so the hook and the repo-wide CI run cannot disagree.
MAX_BYTES=4194304

# Assembled from two halves so this file does not contain the marker it
# searches for, which would make the repo-wide run flag itself.
KEY_MARKER='-----BEGIN [A-Z0-9 ]*PRIVATE KEY'
KEY_MARKER="${KEY_MARKER}-----"

# The Google Workspace SSO client secret has a fixed prefix. Assembled the same
# way, for the same reason. The suffix class is what Google issues; the length
# floor keeps a doc that merely names the prefix from tripping it.
SECRET_MARKER='GOCSPX'
SECRET_MARKER="${SECRET_MARKER}-[A-Za-z0-9_-]{20,}"

failed=0

# $1 = path, $2 = what is wrong, $3 = what to do about it. Every failure says
# the third thing: a gate that only reports is a gate people learn to skip.
fail() {
  printf '\n  %s\n    %s\n    -> %s\n' "$1" "$2" "$3" >&2
  failed=1
}

check_file() {
  path=$1

  # Neither caller should hand us a path that is not there — the hook's list
  # excludes deletions and the CI list is what git already tracks — but a
  # unicode path that git chose to quote can name something we cannot open.
  # Skip it rather than fail the commit on a quoting artefact.
  [ -f "$path" ] || return 0

  # --- an environment file must never be committed ---
  # .env carries the Google Workspace SSO client id and secret that gate the
  # desktop app. It is gitignored, so reaching this check at all means someone
  # ran `git add -f`.
  case ${path##*/} in
    .env.example) ;;
    .env | .env.* | .envrc)
      fail "$path" \
        "An environment file is staged. .env holds the Google Workspace SSO client secret." \
        "git restore --staged '$path' - document the variable name in .env.example instead."
      return 0
      ;;
  esac

  # --- size ---
  # `wc -c < file` rather than `stat`: one spelling that works on both BSD and
  # GNU, and it prints the count alone, so a filename with a space in it cannot
  # be misparsed.
  # macOS pads `wc` output with leading spaces; strip them so the message reads
  # as a number rather than a column.
  bytes=$(wc -c < "$path" | tr -d '[:space:]')
  if [ "$bytes" -gt "$MAX_BYTES" ]; then
    fail "$path" \
      "$bytes bytes, over the $MAX_BYTES-byte limit." \
      "Build artifacts (dmg, zip, database snapshots) do not belong in git - publish them to a Release."
  fi

  # --- a private key must never be committed ---
  # -I skips binaries, so the brand icons cost one read and no scan.
  if grep -qIE -- "$KEY_MARKER" "$path" 2>/dev/null; then
    fail "$path" \
      "Contains a private key block." \
      "Remove it and rotate the key - it is compromised the moment it is committed."
  fi

  # --- the SSO client secret must never be committed, whatever the file ---
  # The .env check above catches the file it belongs in; this catches the value
  # pasted anywhere else: a fixture, a JSON blob, a log, a doc.
  if grep -qIE -- "$SECRET_MARKER" "$path" 2>/dev/null; then
    fail "$path" \
      "Contains what looks like the Google Workspace SSO client secret." \
      "Remove it and rotate the secret in the Google Cloud console - it is compromised once committed."
  fi

  # --- console.log in shipped server code ---
  # "All diagnostic output goes through the structured logger, never
  # console.log" (LLM coding agent documents/CH3 Coding Agent.md 6.8).
  # Matching `console.log(` rather than `console.log`, because apps/server
  # names a run-directory file "console.log" and a comment mentions it, and
  # neither of those is a call.
  case $path in
    apps/server/src/*.test.ts | apps/server/src/*.test.tsx) ;;
    apps/server/src/*.ts | apps/server/src/*.tsx)
      if grep -qE 'console\.log\(' "$path" 2>/dev/null; then
        fail "$path" \
          "Calls console.log in shipped server code." \
          "Log through apps/server/src/serverLogger.ts - console.log bypasses log-level filtering."
      fi
      ;;
  esac
}

if [ "${1-}" = "--all" ]; then
  # What is not tracked is not our problem, and asking git keeps node_modules,
  # dist and .repos out without repeating an ignore list here. Split on
  # newlines only: a `for` over unquoted `$files` would otherwise break
  # "LLM coding agent documents/..." into three paths. Not a pipeline into
  # `while`, because that runs in a subshell and `failed` would not survive it.
  files=$(git ls-files)
  saved_ifs=$IFS
  IFS='
'
  for path in $files; do
    IFS=$saved_ifs
    check_file "$path"
    IFS='
'
  done
  IFS=$saved_ifs
else
  # No arguments means no staged file matched the glob. Nothing to check.
  for path in "$@"; do
    check_file "$path"
  done
fi

if [ "$failed" -ne 0 ]; then
  printf '\nHygiene check failed. Fix the files above; `vp run hygiene` checks the whole tree.\n' >&2
  exit 1
fi
